const notesActions = {
	SET_NOTES_SUCCESS: "SET_NOTES_SUCCESS",
	SET_NOTES_ERROR: "SET_NOTES_ERROR",
	RESET_NOTES: "RESET_NOTES",
	SHOW_NEW_NOTE_FORM: "SHOW_NEW_NOTE_FORM",
	SET_ARCHIVES: "SET_ARCHIVES",
	EDIT_ARCHIVES: "EDIT_ARCHIVES",
    ADD_LABEL: 'ADD_LABEL',
};

const authActions = {
    INIT_AUTH: 'INIT_AUTH',
    RESET_AUTH: 'RESET_AUTH'
}

export { notesActions, authActions };